esphome:
  name: json-automation-demo
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "YourWiFi"
  password: "YourPassword"

logger:
  level: DEBUG

api:
  password: ""

ota:
  password: ""

preferences:
  flash_write_interval: 5min

external_components:
  - source:
      type: local
      path: components

json_automation:
  id: my_automations
  json_data: |
    {
      "automations": [
        {
          "id": "light_on_motion",
          "trigger": {
            "type": "binary_sensor",
            "condition": "on_press",
            "parameters": {
              "sensor_id": "motion_sensor"
            }
          },
          "actions": [
            "light.turn_on: living_room_light",
            {
              "type": "delay",
              "duration": "5min"
            },
            "light.turn_off: living_room_light"
          ]
        },
        {
          "id": "temperature_alert",
          "trigger": {
            "type": "sensor",
            "condition": "on_value_range",
            "parameters": {
              "sensor_id": "temperature",
              "above": "25.0"
            }
          },
          "actions": [
            "switch.turn_on: fan",
            "logger.log: Temperature too high!"
          ]
        }
      ]
    }
  on_automation_loaded:
    then:
      - logger.log: 
          format: "Automations loaded successfully: %s"
          args: ['data.c_str()']
  on_json_error:
    then:
      - logger.log:
          format: "JSON Error: %s"
          args: ['error.c_str()']
          level: ERROR

binary_sensor:
  - platform: gpio
    pin: 14
    name: "Motion Sensor"
    id: motion_sensor

sensor:
  - platform: dht
    pin: 4
    temperature:
      name: "Temperature"
      id: temperature
    humidity:
      name: "Humidity"

light:
  - platform: binary
    name: "Living Room Light"
    id: living_room_light
    output: light_output

output:
  - platform: gpio
    pin: 12
    id: light_output

switch:
  - platform: gpio
    pin: 13
    name: "Fan"
    id: fan

button:
  - platform: template
    name: "Load Custom Automation"
    on_press:
      - json_automation.load_json:
          id: my_automations
          json_data: |
            {
              "automations": [
                {
                  "id": "custom_automation",
                  "trigger": {
                    "type": "time",
                    "condition": "on_time",
                    "parameters": {
                      "hour": "18",
                      "minute": "0"
                    }
                  },
                  "actions": [
                    "light.turn_on: living_room_light"
                  ]
                }
              ]
            }
      - json_automation.save_json:
          id: my_automations

  - platform: template
    name: "Execute Light Automation"
    on_press:
      - json_automation.execute:
          id: my_automations
          automation_id: "light_on_motion"
